artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/samithcsachi/Machine_Learning_Projects/main/Wine%20Quality%20Prediction%20Analysis%20(Classification)/winequalityN.csv
  local_data_file: artifacts/data_ingestion/data.zip
  local_data_file: artifacts/data_ingestion/data/winequalityN.csv


data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data/winequalityN.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data/winequalityN.csv


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib

 
